# Generated by Django 3.2.3 on 2021-05-15 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20210515_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
