# Generated by Django 3.2.3 on 2021-05-15 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20210515_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table_no',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='restaurant.tablebooking'),
            preserve_default=False,
        ),
    ]
