# Generated by Django 3.2.3 on 2021-05-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_order_table_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.JSONField(default={1: 1}),
            preserve_default=False,
        ),
    ]
