# Generated by Django 3.2.2 on 2021-05-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_auto_20210515_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='category',
        ),
        migrations.AddField(
            model_name='menu',
            name='time_to_prepare',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
